String LANDING1 =
"<html>"
" <head>"
"    <meta name='format-detection' content='telephone=no'>"
"    <meta name='msapplication-tap-highlight' content='no'>"
"    <link rel='icon' href='data:,'>"
"    <meta name='viewport' content='initial-scale=1, width=device-width, viewport-fit=cover'>"
"    <style>"
"      *{font-family:'Raleway', Helvetica, sans-serif;color:#fff;}"
"      body{background-color:#1E2832;text-align: center;display: inline-block !important;width: 100%;}"
"      #banner{padding:5em 2em 3em 2em;background-color:#1E2832;text-align:center;}"
"      h2{font-size:1.5em;padding:0;line-height:1.5em;}"
"      .actions{padding: 0;width:100%;max-width: 500px; display: inline-block;}"
"      input{"
"        border-radius: 4px;"
"        border-style: solid;"
"        border-width: 1px;"
"        display: block;"
"        outline: 0;"
"        padding: 0 1em;"
"        text-decoration: none;"
"        width: 100%;"
"        background-color: rgba(144, 144, 144, 0.075);"
"        border-color: rgba(144, 144, 144, 0.25);"
"        height: 3.5em;"
"        font-size: 12pt;"
"        font-weight: 400;"
"        line-height: 2em; "
"      }"
"       #estadowifi{text-align:center;margin:1em 0;}"
"      input[type='submit'].special{"
"        background-color: #51BAA4;"
"        transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;"
"        border-radius: 2.5em;"
"        border: 0;"
"        cursor: pointer;"
"        display: inline-block;"
"        font-weight: 700;"
"        height: 2.85em;"
"        line-height: 2.95em;"
"        font-size: 12pt;"
"        width: 49%;"
"        padding: 0 1.5em;"
"        text-align: center;"
"        text-decoration: none;"
"        text-transform: uppercase;"
"        white-space: nowrap;"
"      }"
"    </style>"
"    <title>BOTS</title>"
"  </head>"
"  <body class='landing'>"
"    <div id='banner'>"
"      <h2 id='deviceready'>BOTS</h2>"
"      <ul class='actions'>"
"        <div class='app'>"
"          <div class='event received' style='display: block;'>"
"            <div id='loginmod'> "
"              <h5>CONFIGURACION WIFI</h5>"
"              <form action='wificonfig' method='post'>"/*/////WIFICONFIG/////*/
"                <input style='display:none' name='action' value='login'/>"
"                <div class='12u$(xsmall)'>"
"                  <input style='margin: 1em 0em' id='user' name='STAssid' placeholder='SSID' type='text' />"
"                </div>"
"                <div class='12u$(xsmall)'>"
"                  <input style='margin: 1em 0em' id='pass' name='STApassword' placeholder='PASSWORD' type='text' />"
"                </div>"
"              <div id='result'></div>"
"              <div class='actions' style='margin:2em 0;'>"
"                <div>"
"                  <input style='min-width:49%' id='login' type='submit' class='special' value='CONECTAR' />"
"                </div>"
"              </div>"
"              </form>";
String LANDING2=
"            </div>"
"          </div>"
"        </div>"
"      </ul>"
"    </div>"
" </body>"
"</html>";
String TEMP =
"<!DOCTYPE html>"
"<html>"
  "<head>"
    "<meta charset=utf-8>"
    "<title>CONECTANDO...</title>"
    "<style>*{font-family:'Raleway', Helvetica, sans-serif;color:#fff;}body{background-color:#1E2832;}</style>"
  "</head>"
  "<body>"
    "<h2>CONECTANDO...</h2>"
    "<div id='trigger'></div>" 
  "</body>"
  "<script type='text/javascript'>"
    "document.getElementById('trigger').addEventListener('load', wait(12000));"
    "function wait(ms){"
      "var start = new Date().getTime();var end = start;"
      "while(end < start + ms){end = new Date().getTime();}"
        "window.location.href = '/';"
    "}"
  "</script>"
"</html>";
